name: d8-decoupled
recipe: drupal8
config:
  via: nginx
  webroot: backend/web
  xdebug: true
services:
  node:
    type: node
    overrides:
      ports:
        - 3000:3000
    globals:
      gulp-cli: latest
tooling:
  drush:
    service: appserver
    cmd:
      - drush --root=/app/backend/web
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
